name: meka_omnibase_control_component
version: iss
joint_array_component: m3joint_array_mb7
pwr_component: m3pwr_pwr042

param:
    #ignored
    xd_max: 0.45
    xdd_max: 0.25
    td_max: 0.60
    tdd_max: 0.40

    # pi/6, 5pi/6, -5pi/6, -pi/6 
    alpha: [0.5236, 2.6180, -2.6180, -0.5236] 
    l: [0.2678, 0.2678, 0.2678, 0.2678]
    d: [0.0200, 0.0200, 0.0200, 0.0200]
    r: [0.0550, 0.0550, 0.0550, 0.0550]
    # Offsets and ratios applied before sending to model:
    beta_offset: [1.83259265359,1.33527265359,1.83259265359,1.30909265359]

    beta_ratio: [1.0, 1.0, 1.0, 1.0] 
    phid_ratio: [1.0, 1.0, 1.0, 1.0] 
    # Ratios applied before sending velocities to casters.
    # NOTE: If caster control is valid, these should be the same as the other
    # two ratios:
    des_betad_ratio: [1.0, 1.0, 1.0, 1.0] 
    des_phid_ratio: [1.0, 1.0, 1.0, 1.0] 

    # TODO: Real values!
    betad_max: [12.0, 12.0, 12.0, 12.0]
    betadd_max: [3.0, 3.0, 3.0, 3.0]
    phid_max: [3.0, 3.0, 3.0, 3.0]
    phidd_max: [6.0, 6.0, 6.0, 6.0]

    bdmax_ratio: 1.2

    tq_max:     2500.0 #1500
    tq_sum_max: 8000.0  #2500

    #casters:
    Ns: 4.0000 # 96/24
    Nt: 2.4286 # 85/35
    Nw: 5.0000 # Should be 32/16, but somehow velocities are twice what they should be.

    k_ed_p:  [-14.0,-14.0,-14.0,-14.0] #18
    k_ed_i:  [-0.2,-0.2,-0.2,-0.2] # 0.04 
    k_ed_d:  [-0.0,-0.0,-0.0,-0.0] #0.4
    k_ed_i_limit: [800.0,800.0,800.0,800.0]
    k_ed_i_range: [800.0,800.0,800.0,800.0]
